// Mocks generated by Mockito 5.4.6 from annotations
// in roadmindphone/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:roadmindphone/database_helper.dart' as _i5;
import 'package:roadmindphone/main.dart' as _i3;
import 'package:roadmindphone/project_index_page.dart' as _i4;
import 'package:sqflite/sqflite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProject_1 extends _i1.SmartFake implements _i3.Project {
  _FakeProject_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSession_2 extends _i1.SmartFake implements _i4.Session {
  _FakeSession_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i5.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i6.Future<_i2.Database>.value(
              _FakeDatabase_0(this, Invocation.getter(#database)),
            ),
          )
          as _i6.Future<_i2.Database>);

  @override
  _i6.Future<_i3.Project> create(_i3.Project? project) =>
      (super.noSuchMethod(
            Invocation.method(#create, [project]),
            returnValue: _i6.Future<_i3.Project>.value(
              _FakeProject_1(this, Invocation.method(#create, [project])),
            ),
          )
          as _i6.Future<_i3.Project>);

  @override
  _i6.Future<_i4.Session> createSession(_i4.Session? session) =>
      (super.noSuchMethod(
            Invocation.method(#createSession, [session]),
            returnValue: _i6.Future<_i4.Session>.value(
              _FakeSession_2(
                this,
                Invocation.method(#createSession, [session]),
              ),
            ),
          )
          as _i6.Future<_i4.Session>);

  @override
  _i6.Future<_i3.Project> readProject(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#readProject, [id]),
            returnValue: _i6.Future<_i3.Project>.value(
              _FakeProject_1(this, Invocation.method(#readProject, [id])),
            ),
          )
          as _i6.Future<_i3.Project>);

  @override
  _i6.Future<List<_i3.Project>> readAllProjects() =>
      (super.noSuchMethod(
            Invocation.method(#readAllProjects, []),
            returnValue: _i6.Future<List<_i3.Project>>.value(<_i3.Project>[]),
          )
          as _i6.Future<List<_i3.Project>>);

  @override
  _i6.Future<List<_i4.Session>> readAllSessionsForProject(int? projectId) =>
      (super.noSuchMethod(
            Invocation.method(#readAllSessionsForProject, [projectId]),
            returnValue: _i6.Future<List<_i4.Session>>.value(<_i4.Session>[]),
          )
          as _i6.Future<List<_i4.Session>>);

  @override
  _i6.Future<int> update(_i3.Project? project) =>
      (super.noSuchMethod(
            Invocation.method(#update, [project]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<int> updateSession(_i4.Session? session) =>
      (super.noSuchMethod(
            Invocation.method(#updateSession, [session]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<int> delete(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<int> deleteSession(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSession, [id]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<dynamic> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i6.Future<dynamic>.value(),
          )
          as _i6.Future<dynamic>);
}
