// Mocks generated by Mockito 5.4.6 from annotations
// in roadmindphone/test/features/project/data/repositories/project_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:roadmindphone/features/project/data/datasources/project_local_data_source.dart'
    as _i3;
import 'package:roadmindphone/features/project/data/models/project_model.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProjectModel_0 extends _i1.SmartFake implements _i2.ProjectModel {
  _FakeProjectModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProjectLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProjectLocalDataSource extends _i1.Mock
    implements _i3.ProjectLocalDataSource {
  MockProjectLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ProjectModel> createProject(_i2.ProjectModel? project) =>
      (super.noSuchMethod(
            Invocation.method(#createProject, [project]),
            returnValue: _i4.Future<_i2.ProjectModel>.value(
              _FakeProjectModel_0(
                this,
                Invocation.method(#createProject, [project]),
              ),
            ),
          )
          as _i4.Future<_i2.ProjectModel>);

  @override
  _i4.Future<_i2.ProjectModel> getProject(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getProject, [id]),
            returnValue: _i4.Future<_i2.ProjectModel>.value(
              _FakeProjectModel_0(this, Invocation.method(#getProject, [id])),
            ),
          )
          as _i4.Future<_i2.ProjectModel>);

  @override
  _i4.Future<List<_i2.ProjectModel>> getAllProjects() =>
      (super.noSuchMethod(
            Invocation.method(#getAllProjects, []),
            returnValue: _i4.Future<List<_i2.ProjectModel>>.value(
              <_i2.ProjectModel>[],
            ),
          )
          as _i4.Future<List<_i2.ProjectModel>>);

  @override
  _i4.Future<_i2.ProjectModel> updateProject(_i2.ProjectModel? project) =>
      (super.noSuchMethod(
            Invocation.method(#updateProject, [project]),
            returnValue: _i4.Future<_i2.ProjectModel>.value(
              _FakeProjectModel_0(
                this,
                Invocation.method(#updateProject, [project]),
              ),
            ),
          )
          as _i4.Future<_i2.ProjectModel>);

  @override
  _i4.Future<void> deleteProject(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProject, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<int> getProjectsCount() =>
      (super.noSuchMethod(
            Invocation.method(#getProjectsCount, []),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<_i2.ProjectModel>> searchProjects(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchProjects, [query]),
            returnValue: _i4.Future<List<_i2.ProjectModel>>.value(
              <_i2.ProjectModel>[],
            ),
          )
          as _i4.Future<List<_i2.ProjectModel>>);

  @override
  _i4.Future<bool> projectExists(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#projectExists, [id]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}
