// Mocks generated by Mockito 5.4.6 from annotations
// in roadmindphone/test/features/project/presentation/bloc/project_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:roadmindphone/core/error/failures.dart' as _i5;
import 'package:roadmindphone/core/usecases/usecase.dart' as _i9;
import 'package:roadmindphone/features/project/domain/entities/project_entity.dart'
    as _i6;
import 'package:roadmindphone/features/project/domain/usecases/create_project.dart'
    as _i3;
import 'package:roadmindphone/features/project/domain/usecases/delete_project.dart'
    as _i11;
import 'package:roadmindphone/features/project/domain/usecases/get_all_projects.dart'
    as _i8;
import 'package:roadmindphone/features/project/domain/usecases/get_project.dart'
    as _i7;
import 'package:roadmindphone/features/project/domain/usecases/search_projects.dart'
    as _i12;
import 'package:roadmindphone/features/project/domain/usecases/update_project.dart'
    as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CreateProject].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateProject extends _i1.Mock implements _i3.CreateProject {
  MockCreateProject() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ProjectEntity>> call(
    _i3.CreateProjectParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.ProjectEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i6.ProjectEntity>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.ProjectEntity>>);
}

/// A class which mocks [GetProject].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetProject extends _i1.Mock implements _i7.GetProject {
  MockGetProject() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ProjectEntity>> call(
    _i7.GetProjectParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.ProjectEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i6.ProjectEntity>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.ProjectEntity>>);
}

/// A class which mocks [GetAllProjects].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllProjects extends _i1.Mock implements _i8.GetAllProjects {
  MockGetAllProjects() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.ProjectEntity>>> call(
    _i9.NoParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.ProjectEntity>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.ProjectEntity>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.ProjectEntity>>>);
}

/// A class which mocks [UpdateProject].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateProject extends _i1.Mock implements _i10.UpdateProject {
  MockUpdateProject() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ProjectEntity>> call(
    _i10.UpdateProjectParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.ProjectEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i6.ProjectEntity>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.ProjectEntity>>);
}

/// A class which mocks [DeleteProject].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteProject extends _i1.Mock implements _i11.DeleteProject {
  MockDeleteProject() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> call(
    _i11.DeleteProjectParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);
}

/// A class which mocks [SearchProjects].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchProjects extends _i1.Mock implements _i12.SearchProjects {
  MockSearchProjects() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.ProjectEntity>>> call(
    _i12.SearchProjectsParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.ProjectEntity>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.ProjectEntity>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.ProjectEntity>>>);
}
