// Mocks generated by Mockito 5.4.6 from annotations
// in roadmindphone/test/features/project/presentation/pages/project_list_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;

import 'package:flutter_bloc/flutter_bloc.dart' as _i12;
import 'package:mockito/mockito.dart' as _i1;
import 'package:roadmindphone/features/project/domain/usecases/create_project.dart'
    as _i2;
import 'package:roadmindphone/features/project/domain/usecases/delete_project.dart'
    as _i6;
import 'package:roadmindphone/features/project/domain/usecases/get_all_projects.dart'
    as _i4;
import 'package:roadmindphone/features/project/domain/usecases/get_project.dart'
    as _i3;
import 'package:roadmindphone/features/project/domain/usecases/search_projects.dart'
    as _i7;
import 'package:roadmindphone/features/project/domain/usecases/update_project.dart'
    as _i5;
import 'package:roadmindphone/features/project/presentation/bloc/project_bloc.dart'
    as _i9;
import 'package:roadmindphone/features/project/presentation/bloc/project_event.dart'
    as _i11;
import 'package:roadmindphone/features/project/presentation/bloc/project_state.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCreateProject_0 extends _i1.SmartFake implements _i2.CreateProject {
  _FakeCreateProject_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetProject_1 extends _i1.SmartFake implements _i3.GetProject {
  _FakeGetProject_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetAllProjects_2 extends _i1.SmartFake
    implements _i4.GetAllProjects {
  _FakeGetAllProjects_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdateProject_3 extends _i1.SmartFake implements _i5.UpdateProject {
  _FakeUpdateProject_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDeleteProject_4 extends _i1.SmartFake implements _i6.DeleteProject {
  _FakeDeleteProject_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSearchProjects_5 extends _i1.SmartFake
    implements _i7.SearchProjects {
  _FakeSearchProjects_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProjectState_6 extends _i1.SmartFake implements _i8.ProjectState {
  _FakeProjectState_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProjectBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockProjectBloc extends _i1.Mock implements _i9.ProjectBloc {
  MockProjectBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CreateProject get createProject =>
      (super.noSuchMethod(
            Invocation.getter(#createProject),
            returnValue: _FakeCreateProject_0(
              this,
              Invocation.getter(#createProject),
            ),
          )
          as _i2.CreateProject);

  @override
  _i3.GetProject get getProject =>
      (super.noSuchMethod(
            Invocation.getter(#getProject),
            returnValue: _FakeGetProject_1(
              this,
              Invocation.getter(#getProject),
            ),
          )
          as _i3.GetProject);

  @override
  _i4.GetAllProjects get getAllProjects =>
      (super.noSuchMethod(
            Invocation.getter(#getAllProjects),
            returnValue: _FakeGetAllProjects_2(
              this,
              Invocation.getter(#getAllProjects),
            ),
          )
          as _i4.GetAllProjects);

  @override
  _i5.UpdateProject get updateProject =>
      (super.noSuchMethod(
            Invocation.getter(#updateProject),
            returnValue: _FakeUpdateProject_3(
              this,
              Invocation.getter(#updateProject),
            ),
          )
          as _i5.UpdateProject);

  @override
  _i6.DeleteProject get deleteProject =>
      (super.noSuchMethod(
            Invocation.getter(#deleteProject),
            returnValue: _FakeDeleteProject_4(
              this,
              Invocation.getter(#deleteProject),
            ),
          )
          as _i6.DeleteProject);

  @override
  _i7.SearchProjects get searchProjects =>
      (super.noSuchMethod(
            Invocation.getter(#searchProjects),
            returnValue: _FakeSearchProjects_5(
              this,
              Invocation.getter(#searchProjects),
            ),
          )
          as _i7.SearchProjects);

  @override
  _i8.ProjectState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeProjectState_6(this, Invocation.getter(#state)),
          )
          as _i8.ProjectState);

  @override
  _i10.Stream<_i8.ProjectState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i10.Stream<_i8.ProjectState>.empty(),
          )
          as _i10.Stream<_i8.ProjectState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i11.ProjectEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i11.ProjectEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i8.ProjectState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i11.ProjectEvent>(
    _i12.EventHandler<E, _i8.ProjectState>? handler, {
    _i12.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i12.Transition<_i11.ProjectEvent, _i8.ProjectState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  void onChange(_i12.Change<_i8.ProjectState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}
